# Generated by Django 5.2.4 on 2025-07-08 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialspace',
            name='agent_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorialspace',
            name='agent_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memorialspace',
            name='profile_image',
            field=models.ImageField(blank=True, default='memorials/profile/default_profile.png', null=True, upload_to='memorials/profile/'),
        ),
        migrations.CreateModel(
            name='CondolenceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('flower_image', models.CharField(choices=[('condolences/flower/default_flower.png', 'flower1'), ('condolences/flower/flower2.png', 'flower2'), ('condolences/flower/flower3.png', 'flower3'), ('condolences/flower/flower4.png', 'flower4'), ('condolences/flower/flower5.png', 'flower5'), ('condolences/flower/flower6.png', 'flower6'), ('condolences/flower/flower7.png', 'flower7')], default='condolences/flower/default_flower.png', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorial_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='memorial.memorialspace')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
