# Generated by Django 5.2.4 on 2025-07-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_step', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, '암컷'), (2, '수컷')], null=True)),
                ('care', models.TextField(blank=True, null=True)),
                ('feeding', models.TextField(blank=True, null=True)),
                ('hospital', models.TextField(blank=True, null=True)),
                ('care_notes', models.TextField(blank=True, null=True)),
                ('funeral_wishes', models.TextField(blank=True, null=True)),
                ('caretaker', models.CharField(blank=True, max_length=30, null=True)),
                ('care_cost_plan', models.TextField(blank=True, null=True)),
                ('substitute_plan', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCarePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_illness', models.BooleanField(blank=True, null=True)),
                ('hospice_care', models.TextField(blank=True, null=True)),
                ('life_sustaining_treatment', models.PositiveSmallIntegerField(blank=True, choices=[(1, '연명치료를 원해요.'), (2, '연명치료를 원치 않아요.')], null=True)),
                ('organ_and_tissue_donation', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(blank=True, max_length=30, null=True)),
                ('guardian_contact', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funeral_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '일반 장례식'), (2, '가족장'), (3, '무빈소 장례식'), (4, '종교장'), (5, '기타')], null=True)),
                ('invited_guests', models.TextField(blank=True, null=True)),
                ('funeral_wishes', models.TextField(blank=True, null=True)),
                ('grave_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '매장묘'), (2, '봉안묘'), (3, '납골당'), (4, '수목장'), (5, '잔디장'), (6, '기타')], null=True)),
                ('grave_preparation', models.TextField(blank=True, null=True)),
                ('tombstone_inscription', models.TextField(blank=True, null=True)),
                ('memorial_service_wishes', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_record', models.TextField(blank=True, null=True)),
                ('father_record', models.TextField(blank=True, null=True)),
                ('siblings_record', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_list', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='BelongingsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_to_discard', models.TextField(blank=True, null=True)),
                ('items_to_distribute', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, '여성'), (2, '남성')], null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_domicile', models.CharField(blank=True, max_length=100, null=True)),
                ('current_diseases', models.TextField(blank=True, null=True)),
                ('past_diseases', models.TextField(blank=True, null=True)),
                ('constitution', models.CharField(blank=True, max_length=100, null=True)),
                ('family_tree', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_meaning', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('favorites', models.TextField(blank=True, null=True)),
                ('preferences', models.TextField(blank=True, null=True)),
                ('school_days', models.TextField(blank=True, null=True)),
                ('work_and_social_life', models.TextField(blank=True, null=True)),
                ('writings', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
        migrations.CreateModel(
            name='WillAndInheritance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_to_parents', models.TextField(blank=True, null=True)),
                ('message_to_friends', models.TextField(blank=True, null=True)),
                ('will_text', models.TextField(blank=True, null=True)),
                ('assets_and_distribution', models.TextField(blank=True, null=True)),
                ('credit_card_list', models.TextField(blank=True, null=True)),
                ('pension_and_insurance', models.TextField(blank=True, null=True)),
                ('debts', models.TextField(blank=True, null=True)),
                ('will_storage_location', models.TextField(blank=True, null=True)),
                ('will', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='will.will')),
            ],
        ),
    ]
