# Generated by Django 5.2.1 on 2025-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
