# Generated by Django 5.2.4 on 2025-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0002_will_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, '암컷'), (2, '수컷')]),
        ),
    ]
