# Generated by Django 5.2.1 on 2025-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0003_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='constitution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '여성'), (2, '남성')], null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='registered_domicile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funeral',
            name='funeral_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '일반 장례식'), (2, '가족장'), (3, '무빈소 장례식'), (4, '종교장'), (5, '기타')], null=True),
        ),
        migrations.AlterField(
            model_name='funeral',
            name='grave_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '매장묘'), (2, '봉안묘'), (3, '납골당'), (4, '수목장'), (5, '잔디장'), (6, '기타')], null=True),
        ),
        migrations.AlterField(
            model_name='medicalcarepreparation',
            name='life_sustaining_treatment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '연명치료를 원해요.'), (2, '연명치료를 원치 않아요.')], null=True),
        ),
        migrations.AlterField(
            model_name='medicalcarepreparation',
            name='terminal_illness',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '암컷'), (2, '수컷')], null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
